USER_LIB_PATH := $(realpath ./lib)
ARDUINO_LIBS  := Wire HPRGB2
#BOARD_TAG     := uno
BOARD_TAG     := pro5v328
ARDUINO_PORT  := /dev/ttyUSB0
CXXFLAGS      += -std=gnu++11
CFLAGS        += -std=gnu++11
#AVRDUDE_ISP_BAUDRATE := 19200

include ../../../Arduino-Makefile/Arduino.mk
